gempy-project/gempy

gempy/core/grid_modules/grid_types.py
fixed bug in create_regular_grid_3d where incorrect resolution is for y and z axis (`resolution[0]` is only the x axis resolution)
this change updates the function to do what `get_dx_dy_dz` does
=> fixed bug in create_regular_grid_3d

gempy/core/data.py
creating sections seems to have been slightly broken in a recent version of master, this fix passes the required regular grid to the sections, although if there is a different way to instantiate sections that is incompatible with the fix then this pr can be ignored if that change is documented
=> fixes sections init as regular grid is needed

gempy/utils/docstring.py
**Addressing epic issue #279.**
Added some explanation on the orientation values dip, azimuth and polarity in the docstrings.py.
This was requested by users, as it was unclear how we actually handle these values, azimuth in particular, in GemPy (there are different approaches in general).
_Please check if this explanation is placed in the correct place, is not too long and if you agree with it @Leguark._
Additionally fixed smaller mistakes in the other texts in the docstring.
=> Extend orientation docstring + fix small mistakes

gempy/core/gempy_api.py, test/test_core/test_integration.py
When using modify_kriging_parameters and recompiling the interpolator, the changes are not taken into account and reset to default.
We should be able to change the Covariance/Variogram range in the kriging interpolation. As of now changing the range parameter directly in the `model.additional_data` object or using `modify_kriging_parameter` is reset as soon as the interpolator is recompiled.
The test now checks if the range in the `additional_data` object is the same before and after recompiling. 
Relates to #322 
=> [BUG] Added assert to test_kriging_mutation

gempy/core/data.py, gempy/core/gempy_api.py, gempy/core/model.py, test/test_core/test_integration.py
I implemented a feature, where pandas dataframe objects can be passed directly to read_data method. This is helpful for a project I am working on, where gempy needs to be integrated in another framework
=> Added possibility to pass pandas dataframe objects directly to read_data()

.travis.yml, docs/source/conf.py, examples/integrations/gempy_discretize_emg3d.py
- Fix Travis to include the emg3d-example in the gallery.
- Slight overhaul of .travis.yml (mostly not touching the structure of it):
- Using the default miniconda-approach instead of the bootstrapping approach (https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/use-conda-with-travis-ci.html).
- Whenever possible getting package from conda-forge.
- Using a conda-env.
- Always installing gempy (before that was only done for 'deploy').
- Update emg3d-example to reflect changes in emg3d.
- Remove double entry ` from sphinx_gallery.sorting import FileNameSortKey ` in `docs/source/conf.py`.
=> Fix Travis for emg3d/pymc3.

gempy/core/data.py, test/test_core/test_colors.py
Adds random hexcolor generation to the surface color dict generation to avoid problems with too many surfaces (so far 66 was the maximum).
Fixes #451 
Supersedes #462 and #452 .
I am expecting the Travis check to fail at first because of #461. There might be a bug in the changes to the Color class which will be difficult to track down given the error messages we've seen so far.
=> 🌈 Fix 451: Adds random color generation for more than 66 surfaces

.travis.yml
Before this change, Travis checks every commit pushed to every branch on gempy's GitHub repository.
Furthermore, making a new branch, even without adding new commits, causes Travis to check the latest commit on the new branch again (#467 ).
With this PR, I propose that Travis only checks the release and master branches. Since we have the following option enabled on the Travis side
all commits pushed to PR branches are still checked. This means that Travis starts testing changes as soon as there is a PR and not until then. I think that this is the ideal behavior.
=> Have Travis only check master, release, and PR branches

.travis.yml
Fixes #502 by freezing the version of pandas installed by Travis to pandas==1.0.5.
This should be a temporary fix. Ideally we will be able to install the latest pandas on master and only freeze versions for releases.
So far I have had trouble writing a MWE for raising a proper issue at the pandas repo. See #502 for progress.
=> Freeze pandas version because of bug in 1.1.0

gempy/plot/visualization_3d.py, gempy/utils/geogrid.py, optional-requirements.txt
Remove pyevtk by using pyvista instead, untested.
=> WIP remove pyevtk and use pyvista instead

gempy/core/model.py
When the X and Y  (Z) columns are missing in a DataFrame, an unclear IndexError message is provided. This PR adds a try-except block to catch this error and to return a proper error message.
=> Raise ValueError for missing Coordinates in DataFrame

gempy/plot/_vista.py, gempy/plot/vista.py, setup.py
Fixes broken PyVista/PyVistaQt import with latest releases.
=> Fix broken PyVista import

setup.py
=> [BUG] Trying to fix pandas version

gempy/plot/visualization_2d.py
=> Fixes issue #688 with slightly inadequate geological map as a result of plot_2d()

gempy/core/interpolator.py
Got another warning in my tests, this time:
`../......lib/python3.9/site-packages/gempy/core/interpolator.py:1: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
from collections import Iterable`
However, `from collections import Iterable` is not even used in `interpolator.py` as all occurrences are currently commented (lines 157-166, lines 180-190).
Cheers Alex
=> 'RemoveCollections'

gempy/core/model.py, test/test_core/test_model.py
toggling a fault back to a erosion series now changes back its color.
Relates to #268
=> [ENH] - add functionality described in #268

README.md
Remove Version Warning in Readme and add information about dependencies
=> Remove Version Warnings and Add Information about DEPs

gempy/core/data_modules/geometric_data.py, test/test_core/test_data_mutation.py
Manually added surface points with `add_surface_points` were allocated to the first created surface.
This was due to a type check solely for `int`. Changed to `isinstance(idx, (int, np.int64))` as somewhere along the creation, `idx` gets changed from `int` to `np.int64`...
Relates to #813 
=> [BUG] surface points added to wrong surface

gempy/plot/plot_api.py
Allows the user to change the font size of the grid labels when `ve=1` by using `gp.plot_3d(geo_model, ... , font_size=12)`. **When `ve` other than `1` is applied, the label size cannot be changed for some reason.** I assume it is a PyVista-related bug as I can reproduce it with a minimal code example. Bug report in the PyVista at https://github.com/pyvista/pyvista/issues/4768
Relates to https://github.com/cgre-aachen/gempy/discussions/818
=> [WIP] FixFontSize

README.md
Adding the publication of Marquetto et al. (2024) with Alexander Jüstel as Co-Autor. In this publication, GemPy was used to create a hydrostratigraphical model in Brazil.
=> Adding Publication

gempy/core/color_generator.py, test/test_core/test_color_generator.py
- Use random colors when no more `hex_color`.
- Ensure that the `up_next` method is consistent with `__next__` when using random colors.
- Fix issue with `_random_hexcolor`, happening once every 16 calls where you end up with less than 6 numbers after the `#`, because of how [lstrip](https://docs.python.org/3/library/stdtypes.html#str.lstrip) works.
- Add tests for each points mentioned above.
Relates to #930 
=> [BUG] ColorsGenerator never returns random_colors

examples/examples/real/Perth_basin.py, requirements/docs_requirements.txt
Added `sphinx_design` to the documentation requirements. This package provides additional directives and roles for Sphinx documentation, enhancing the layout and design capabilities for our documentation.
Relates to #N/A
=> [DOC] Building docs in CI

gempy/core/data/grid.py, test/test_modules/test_marching_cubes.py
=> [ENH/WIP] Adding first test to implement marching cubes

gempy/core/data/geo_model.py, gempy/modules/mesh_extranction/marching_cubes.py, test/test_modules/test_marching_cubes.py
TODO: Needs new version of gempy viewer
Added a new module for mesh extraction using the marching cubes algorithm. The implementation provides a clean way to extract meshes for all structural elements in a geological model.
The new `mesh_extraction` module contains functions to:
- Extract meshes for all structural elements in a model
- Process individual elements with proper coordinate transformations
- Handle the conversion from scalar fields to 3D meshes
Refactored the test_marching_cubes.py to use the new module, significantly simplifying the test code by removing the manual implementation that was previously used.
Relates to #mesh-extraction-enhancement
=> [FEATURE] Add mesh extraction module using marching cubes algorithm

gempy/modules/mesh_extranction/marching_cubes.py, test/test_modules/test_marching_cubes.py
Improved the marching cubes implementation for mesh extraction with proper masking support. The changes include:
1. Added proper masking for lithological groups vs fault groups
2. Fixed scalar field value assignment to structural elements
3. Implemented helper functions to generate masking arrays and set scalar field values
4. Modified the mesh extraction process to correctly handle masks during marching cubes
5. Updated test resolution for better visualization
Relates to mesh extraction functionality
=> [ENH] Improve marching cubes mesh extraction with masking support | GEN-12031

test/test_modules/test_outliers.py
Since the release of gempy v3 we noticed some outliers in the lithology block. These are basically single cells that have a wrong element ID in the lithology block. They generally appear close to surface boundaries and are appearing depending on resolution. This might be caused when mapping sclar field values to int for the lithology block.
As I don't think the isse is related to Octrees or DC I opened a new pull request. This issue will cause problems when reintroducing MC as a meshing approach in #1000 and #1006 .
For now I added a single example as a test (see screenshot). I will add more examples whe I come across them and have time.
=> [BUG] Outliers in gempy v3

gempy/core/data/geo_model.py, gempy/core/data/structural_element.py, gempy/modules/mesh_extranction/marching_cubes.py, test/test_modules/test_marching_cubes.py
Refactored the mesh extraction process using marching cubes algorithm to improve accuracy and efficiency. The main changes include:
1. Renamed `scalar_field` to `scalar_field_at_interface` in the `StructuralElement` class for better clarity
2. Added proper assignment of scalar field values to structural elements
3. Simplified the mesh extraction logic by using the output group's scalar field matrix and mask directly
4. Improved the marching cubes implementation with proper parameters (allow_degenerate=False, method="lewiner")
5. Added comprehensive tests to verify the mesh extraction results
Relates to #mesh-extraction-improvements
=> [ENH] Refactor mesh extraction and add scalar field at interface to structural elements | | GEN-12031

examples/tutorials/ch1_fundamentals/ch1_7_3d_visualization.py, requirements/dev-requirements.txt, requirements/docs_requirements.txt
This PR makes several dependency and functionality updates:
1. Added `dotenv.load_dotenv()` to the 3D visualization tutorial to properly load environment variables
2. Added `make_new_space=False` parameter to the model upload function in the tutorial
3. Replaced the git dependency for subsurface with the PyPI package `subsurface-terra` in dev-requirements
4. Added `liquid-earth-sdk` and `wellpathpy` to the docs requirements
Relates to dependency management and tutorial improvements
=> [BUG] Revive gempy x le connection  GEN-10870

examples/tutorials/z_other_tutorials/video_tutorial_model_3_onlap.py
Uploaded the new onlap example for the video tutorial series.
=> Onlap example for video tutorials

gempy/API/compute_API.py
=> [CLN] Remove legacy backend and unused code

gempy/core/color_generator.py, gempy/core/data/structural_frame.py, gempy/modules/optimize_nuggets/_ops.py, gempy/modules/serialization/save_load.py, test/test_modules/_geophysics_TO_UPDATE/test_gravity.test_gravity.verify/2-layers.approved.txt, test/test_modules/test_faults/test_finite_faults.test_finite_fault_scalar_field_on_fault.verify/fault.approved.txt, test/test_modules/test_grids/test_custom_grid.test_custom_grid.verify/fold.approved.txt, test/test_modules/test_grids/test_grids_sections.test_section_grids.verify/fold.approved.txt, test/test_modules/test_grids/test_grids_sections.test_topography_II.verify/Model1.approved.txt, test/test_modules/test_serialize_model.test_generate_horizontal_stratigraphic_model.verify/Horizontal Stratigraphic Model serialization.approved.txt, test/test_private/test_terranigma/test_nuggets/test_nugget_effect_optimization.py
This PR refactors the `ColorsGenerator` class to use `__post_init__` instead of `__init__` and improves the basement color generation in `StructuralFrame`. The changes include:
- Refactored `ColorsGenerator` to use `__post_init__` for proper dataclass initialization
- Added `color_generator` as a proper field with default factory in `StructuralFrame`
- Improved basement color generation logic to ensure uniqueness
- Fixed a tensor detachment issue in nugget optimization by converting to numpy
- Removed unused imports in serialization and test modules
- Updated test validation settings
Relates to #optimization-and-refactoring
=> [ENH] Fix color generator initialization and improve basement color handling

gempy/API/examples_generator.py, gempy/core/data/grid.py, gempy/core/data/grid_modules/regular_grid.py, gempy/core/data/grid_modules/topography.py, test/test_api/test_initialization_and_compute_api.py, test/test_api/test_model_construction_granular.py
=> Fix main for Python > 11

gempy/core/data/grid.py
=> [CLN] Remove redundant octree level resolution check in grid initialization

examples/examples/real/Hecho.py, gempy/modules/data_manipulation/manipulate_points.py
Added support for name_id_map parameter in add_orientations function to maintain consistent ID mapping between surface points and orientations. Updated the Hecho example to use this parameter and fixed tuple formatting in section_dict. Also enabled validation during serialization in the compute_model call.
Relates to #validation-and-serialization-improvements
=> [ENH] Add name_id_map parameter to add_orientations and enable serialization validation

gempy/core/data/grid.py
Refactored the `regular_grid` method to use the previously defined boolean variables `dense_grid_exists_and_active` and `octree_grid_exists_and_active` for consistency and improved readability, instead of directly checking if the grid objects are not None.
Relates to #grid-refactoring
=> [CLN] Refactor grid selection logic by using active state checks
