gempy-project/gempy

README.md
Looks great! :+1: 
Looking forward to the paper and, on the long run, to the possibility to analyze uncertainties in geological models derived from geophysical data by linking gempy to [pyGIMLi](https://github.com/gimli-org/gimli).
Best wishes
Florian
=> Just a minor doc correction: install.py -> setupy.py install

gempy/decision_making.py
=> DM module continued (loss_abs and loss_sqr)

gempy/interpolator.py
Utilizing sys.setrecursionlimit()
=> Added data_to_pickle method for the InterpolatorData class, experimental

gempy/plotting/visualization.py
apparently `nodes_iter()` was removed and replaced by `nodes()`
=> changed deprecated nodes_iter() to nodes() method

gempy/core/data.py
=> fixed call to reindex_axis

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/question.md, .github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md, test/CONTRIBUTION.md
Addresses issue #270 
Before merging:
- Add and edit templates
=> Add Contribution guidelines

setup.py
Addresses #331 , includes nptyping in setup.py.
=> Add nptyping to setup.py

gempy/plot/plot_api.py, gempy/plot/vista.py
Some fixes and documentation for the new plotting api.
Relates to #278, #321, #304 
=> Plotting fixes

gempy/core/data.py, gempy/core/model.py, test/test_core/test_grids/test_grid.py, test/test_core/test_solution.py
=> Add custom grid tests

README.md
Updated Readme file:
- Added a description of geological features to beginning (to clearly show what can be done)
- Some spell and grammar fixes, refs, etc.
- Removed reference to gif that is not anymore part of repo
- Added installation instructions for MacOSX 10.14 (should also work with MaxOSX 10.15, but I am still on 10.14 at the moment). All steps tested, included some headache-causing issues around theano.
=> Development flow update readme

gempy/core/data.py
Fixed the error for the update of colors for more than 67 surfaces.
=> [BUG] Fixed: colors for more than 67 surfaces.

MANIFEST.in
=> Add the license to the manifest for inclusion in source code

MANIFEST.in
I just realized my pr was not explicit about the include of the license, I don't think it would have broken anything but better to be safe.
fixes typo in #435 
=> Update manifest.in to be explicit

.travis.yml
=> Fix version of discretize installed by Travis

gempy/core/solution.py
this pr just cleans up some code in the solution object to make it easier to read. should not break anything
=> cleaning up some logic in solution.py

gempy/bayesian/fields.py
refactors and expands the probablities and information entropy
functions
now includes total model entropy and fuzziness from the 2012 "Uncertainties
have a meaning" paper.
Modest speedup for probability function, uses scipy for information
entropy calculation enabling base change.
=> Expand/refactor information/uncertainty functions

.travis.yml, gempy/plot/vista.py
Travis is not installing gdal for some mysterious reason
=> - [TRAVIS] split conda install command

docs/source/installation.rst, examples/tutorials/ch1_fundamentals/ch1_1_basics.py
=> basics minor edits

README.md
Update of README with link to published version of Nilgün's paper.
=> Updated README.md with link to Nilgün paper

setup.py
update from master
Relates to #741
=> install sklearn in setup

gempy/api_modules/io.py, gempy/api_modules/setters.py, gempy/core/model.py, gempy/gempy_api.py, gempy/plot/_visualization_2d.py, gempy/plot/vista.py, gempy/plot/visualization_2d.py, gempy/plot/visualization_3d.py, test/test_addons/test_rex_cloud_api.py, test/test_assets/test_magnetics.py
=> [WIP] Fix test warnings

gempy/core/solution.py
reshape solutions.fault_block in the same shape as solutions.lith_block
=> Minor change: Reshape solution.fault_block

README.md
Updated list of publications using GemPy on README
No code contribution :-) 
=> Updated list of publications using GemPy

installation.html
Only updates in documentation:
* installation.html: added info for gempy-viewer
Relates to [#955](https://github.com/gempy-project/gempy/issues/955) Closes [#955](https://github.com/gempy-project/gempy/issues/955)
=> Updated installation.html

docs/source/installation.rst, examples/tutorials/z_other_tutorials/README.rst, examples/tutorials/z_other_tutorials/video_tutorial_model_1.py
The PR contains the changes in the main repo, which triggered the updates in the documentation _gh_pages_ branch (local sphinx run)
=> Updated changes in main repo for consistency with documentation

DevelopersGuide.md, docs/source/index.rst, examples/tutorials/z_other_tutorials/video_tutorial_model_1.py
Changes corresponding to updated documentation:
- Video tutorial
- Changes in index.rst with updates and new figures
- Changes in DeveloperGuide.md with details on documentation update
=> Changes in main corresponding to docu update

examples/tutorials/z_other_tutorials/video_tutorial_model_2_faults.py
Added fault tutorial script for documentation update.
=> [DOC] Added fault tutorial script

README.md, requirements/dev-requirements.txt, test/test_model_types/test_subduction.py, test/test_modules/test_gempy_subsurface.py
=> [DOC] Update subsurface dependency and refactor tests for compatibility

examples/examples/geometries/a01_horizontal_stratigraphic.py, requirements/docs_requirements.txt
Enhanced the horizontal stratigraphic example with comprehensive documentation and additional functionality. The improvements include:
- Added detailed docstrings explaining the purpose of each code section
- Implemented functions to extract mesh vertices and normals from the geological model
- Added capability to export model components to VTK files
- Created functionality to save mesh data to Excel files and convert to XYZ format
- Improved code organization with clear section headers
- Added openpyxl to docs requirements for Excel file handling
Relates to geological model visualization and data export
=> [META] Added openpyxl as requirenment for docs and enhance example

gempy/core/data/grid.py, gempy/core/data/structural_frame.py, gempy/modules/serialization/save_load.py, test/test_modules/_geophysics_TO_UPDATE/test_gravity.test_gravity.verify/2-layers.approved.txt, test/test_modules/test_faults/test_finite_faults.test_finite_fault_scalar_field_on_fault.verify/fault.approved.txt, test/test_modules/test_grids/test_custom_grid.test_custom_grid.verify/fold.approved.txt, test/test_modules/test_grids/test_grids_sections.test_section_grids.verify/fold.approved.txt, test/test_modules/test_grids/test_grids_sections.test_topography_II.verify/Model1.approved.txt, test/test_modules/test_serialize_model.test_generate_horizontal_stratigraphic_model.verify/Horizontal Stratigraphic Model serialization.approved.txt, test/verify_helper.py
Refactored the model serialization system to use ZIP archives instead of raw binary files. This change:
- Implemented `model_to_bytes()` to replace `model_to_binary()`, creating a ZIP archive with header.json, input.bin, and grid.bin
- Added `_load_model_from_bytes()` to replace `_deserialize_binary_file()`, extracting data from the ZIP archive
- Updated references in save_model(), load_model(), and test verification helpers
- Added imports for io and zipfile modules
Relates to #serialization-improvement
=> [ENH] Implement ZIP-based model serialization format
